version: 2
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./patientprogress/deploy.sh"
  build:
    docker:
      - image: node:16.1.0

    working_directory: ~/repo

    steps:
      - checkout:
          post:
            - git fetch --all

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      # - run: npm install --g lerna
      - run: npm install netlify-cli -g

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn ci:test

      - run: git config --global user.email $GITHUB_EMAIL
      - run: git config --global user.name $GITHUB_USER

      - run: git tag
      - run: yarn ci:deploy

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
      - build:
          filters:
            branches:
              only:
                - master
